[project]
name = "streamlit-ws"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "openai>=2.14.0",
    "streamlit>=1.52.2",
    "websocket>=0.2.1",
    "websocket-client>=1.9.0",
]
